[colors]
ansi = [
    "{color0}",
    "{color1}",
    "{color2}",
    "{color3}",
    "{color4}",
    "{color5}",
    "{color6}",
    "{color7}",
]
background = "{background}"
brights = [
    "{color8}",
    "{color9}",
    "{color10}",
    "{color11}",
    "{color12}",
    "{color13}",
    "{color14}",
    "{color15}",
]
cursor_bg = "{cursor}"
cursor_border = "{cursor}"
cursor_fg = "{color0}"
foreground = "{foreground}"
selection_bg = "{color4}"
selection_fg = "{color0}"

