[colors]
background = '{background}8e'
black = '{color0}'
blue = '{color1}'
cursor = '{cursor}'
cyan = '{color2}'
foreground = '{foreground}'
green = '{color3}'
magenta = '{color4}'
red = '{color5}'
tabs = '{foreground}'
tabs-active = '{color6}'
white = '{foreground}'
yellow = '{color7}'
dim-black = '{color0}8e'
dim-blue = '{color1}8e'
dim-cyan = '{color2}8e'
dim-foreground = '{foreground}8e'
dim-green = '{color3}8e'
dim-magenta = '{color4}8e'
dim-red = '{color5}8e'
dim-white = '{color6}8e'
dim-yellow = '{color7}8e'
light-black = '{color9}'
light-blue = '{color10}'
light-cyan = '{color11}'
light-foreground = '{color12}'
light-green = '{color13}'
light-magenta = '{color14}'
light-red = '{color15}'
light-white = '{color9}'
light-yellow = '{color10}'
